### PR TITLE
Fix rootmeta concurrency

### LINKED ISSUE #29: getOrCreateRootMetafeed is not concurrency safe
This screenshot shows the problem pretty well, 3 meta feed messages and 2 seed values.

image

We need to do something similar to what we did in jitdb with only allowing 1 at a time.

### PR DESCRIPTION
**Pull request by arj03**
Should fix #29. Gonna test it now.

### CODE REVIEW

**Comment by arj03** [comment]
Note this is on top of the other PR to allow me to test this

**Comment by arj03** [comment]
Yep, seems to work :)

**Comment by arj03** [comment]
This can be simplied, I'll do this properly tomorrow. Enough for today ;)

**Comment by staltz** [comment]
Very well spotted, good fix, conceptually. I made #31 because it was fun to simplify it.

**Pull request merged**
